[package]
name = "zed_jsonnet"
version = "0.3.2"
edition = "2021"
publish = false
license = "Apache-2.0"

[lib]
path = "src/jsonnet.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.0.6"
